### ISSUE TITLE
Norway coast

### ISSUE THREAD

**Issue by ChipWolf** [geodienst/lighthousemap#10]
There appears to be hundreds along the Norwegian coast that don't correlate with lighthouses.

I'm aware the data is just from OSM, but what's the hypothesis for what we're seeing there?

![image](https://user-images.githubusercontent.com/3164166/150993747-3fd3cd9a-7146-43c9-9ee9-2234d17bbdfb.jpeg)

**Comment by leonmvd** [comment]
Our map shows all kinds of seamark lights, so these can be buoys, beacons etc. as well as lighthouses. See OSM wiki for info: https://wiki.openstreetmap.org/wiki/Seamarks/Lights
