### ISSUE TITLE
OUESSANT 4 lighthouses - some missing

### ISSUE THREAD

**Issue by waldi1992** [geodienst/lighthousemap#11]
I think, only one lighthouse is shown
There are 4 in the area of the island in the bretagne
https://www.google.at/search?client=safari&hl=de-at&tbs=lf:1,lf_ui:1&tbm=lcl&sxsrf=AOaemvLfg59uwE3D3QFsgwgtScUWuz7nUQ:1643126380863&q=ouessant+lighthouse&rflfq=1&num=10&ved=2ahUKEwjw74Hios31AhVogv0HHVR1CwAQtgN6BAgPEAU#rlfi=hd:;si:,48.49073226112701,-5.024415303737699;mv:%5B%5B48.505424811952906,-5.008107472927152%5D,%5B48.41822957340495,-5.170499135524809%5D%5D

**Comment by leonmvd** [comment]
you're welcome to add them correctly in openstreetmap, then our map will be updated every night
