### ISSUE TITLE
Fix range for "Tjuvviki" beacon light (Giant red circle in Norway)

### ISSUE THREAD

**Issue by dannyradden** [geodienst/lighthousemap#13]
The "Tjuvviki" beacon in data-full.json shows a range of 33 Nautical miles which is a mistake that can be traces back to the API that served the data. The correct range should be a much smaller 2 miles according to [this pdf](https://msi.nga.mil/api/publications/download?key=16694312/SFH00000/UpdatedPub115bk.pdf&type=view). You can find it in the PDF if you search for "Tjuviki" (slightly different spelling than the API has but the same coordiantes). You can either just edit your json file or try repulling from the API, but I am not certain I went about fixing the range correctly, so it may or may not be fixed on their side.

**Comment by leonmvd** [comment]
If you edit the light in openstreetmap the changes should be reflected automatically from now on

**Comment by dannyradden** [comment]
> If you edit the light in openstreetmap the changes should be reflected automatically from now on

Cool, that is what I did
