### ISSUE TITLE
Lighthouse missing

### ISSUE THREAD

**Issue by pabekam** [geodienst/lighthousemap#14]
There is a lighthouse missing in Alexandroupolis, Greece

![faros-12-791x1024](https://user-images.githubusercontent.com/79979195/151142924-b1131e37-c7ba-4270-bd2f-df39986ff17c.jpg)

**Comment by PierreMesure** [comment]
Hi, the building [is present on OSM](https://www.openstreetmap.org/way/282628027) but its light characteristics are not. See if you can improve the data!
