### ISSUE TITLE
Missing - Tybee Island lighthouse

### ISSUE THREAD

**Issue by pauldisney** [geodienst/lighthousemap#15]
https://g.page/tybeelighthouse?share

**Comment by PierreMesure** [comment]
Hi Paul, it seems to be because this lighthouse isn't described as one on OSM, [have a look](https://www.openstreetmap.org/way/456451300#map=16/32.0078/-80.8495) and see if you can improve the data.

**Comment by pauldisney** [comment]
Thank you for replying. Here are 2 screenshots, a web link and quote that
may help.

https://en.wikipedia.org/wiki/Tybee_Island_Light

Location Tybee Island <https://en.wikipedia.org/wiki/Tybee_Island>, Georgia
<https://en.wikipedia.org/wiki/Georgia_(U.S._state)>
Coordinates <https://en.wikipedia.org/wiki/Geographic_coordinate_system>
32°01′20″N 80°50′44″W
<https://geohack.toolforge.org/geohack.php?pagename=Tybee_Island_Light&params=32.02223_N_80.84566_W_>

"The beacon is still a functioning navigational aid, still using its
original lens. The site is open to the public and retains its keepers
houses and auxiliary buildings as well as the lighthouse tower.[3]
<https://en.wikipedia.org/wiki/Tybee_Island_Light#cite_note-NPS-3>"

[image: image.png]
[image: image.png]

**Comment by Eric-Sparks** [comment]
I've [added the proper seamark information](https://www.openstreetmap.org/way/456451300/history) to this lighthouse.  Hopefully it'll show up on the map, now.

**Comment by pauldisney** [comment]
Thank you!

**Comment by leonmvd** [comment]
data will sync with osm every night now!
