### ISSUE TITLE
Westerhever missing

### ISSUE THREAD

**Issue by jlai79** [geodienst/lighthousemap#18]
Westerhever lighthouse is missing on the map? Is there missing any required metadata on OSM?
https://www.openstreetmap.org/way/87534169

**Comment by jamesscottbrown** [comment]
This is a sector light - these aren't currently displayed (Issue #1)  but there is a [PR to change this](https://github.com/geodienst/lighthousemap/pull/16).

The root issue is that they use tags like `seamark:light:1:sequence`,  `seamark:light:2:sequence`..., rather than `seamark:light:sequence`.
