### ISSUE TITLE
Enrichment: Great Lakes Lighthouses

### ISSUE THREAD

**Issue by seajaysec** [geodienst/lighthousemap#4]
Most of the Great Lakes' lighthouses are missing from this map. I found the data shared by the Great Lakes Lighthouse Keepers Association here.

https://gllka.maps.arcgis.com/apps/webappviewer/index.html?id=9e1508ae15f9444f9b960aa42e435951&fbclid=IwAR1w5ukx_Rn2PoK6-2bDHygJlOh8uOLLL4zzvRIso7sa0-oMarEWxApgsK0

**Comment by leonmvd** [comment]
If they are in osm the should now be visible on the map
